In [6]:
import numpy as np

C = np.array(
    [
        [1,0,0,0,0,0,0],
        [0,0,1,0,0,0,0],
        [0,0,0,0,0,0,1]
    ]
)
W = np.random.randn(7,3)

print(C.shape)
print(W.shape)

H = np.dot(C,W)

print(W)
print("--------------------------------")
print(H)

[[-0.60366181  0.16809798  0.3096128 ]
 [ 0.30535502 -0.55814516 -1.44096442]
 [ 0.70978053 -1.21075372 -0.05929037]
 [ 1.33691378  0.96876314 -0.56333257]
 [ 0.75922991 -0.11355561 -2.07197189]
 [-1.52603033 -0.05897114  0.38463063]
 [-0.48794978 -1.97427366  1.70992742]]
--------------------------------
[[-0.60366181  0.16809798  0.3096128 ]
 [ 0.70978053 -1.21075372 -0.05929037]
 [-0.48794978 -1.97427366  1.70992742]]


In [8]:
import sys
sys.path.append('./deep')

import numpy as np
from common.layers import MatMul

C = np.array([[1,0,0,0,0,0,0]])
W = np.random.randn(7,3)

layer = MatMul(W)
H = layer.forward(C)

print(W)
print("--------------------------------")
print(H)


[[ 1.63713371  1.06970676 -0.96987425]
 [ 0.14050255 -0.83995006  0.2482509 ]
 [ 0.69397294  1.39937413 -0.47320753]
 [-1.64233857  0.71926946  2.72786475]
 [-0.89016513  0.55398088 -0.58383881]
 [ 0.88485649 -1.29567572 -0.3921314 ]
 [-1.24993195  0.99603214 -1.49792002]]
--------------------------------
[[ 1.63713371  1.06970676 -0.96987425]]


In [10]:
import sys

sys.path.append('./deep')

import numpy as np
from common.layers import MatMul

C0 = np.array([[1,0,0,0,0,0,0]])
C1 = np.array([[0,0,1,0,0,0,0]])
W_in = np.random.randn(7,3)
W_out = np.random.randn(3,7)

in_layer0 = MatMul(W_in)
in_layer1 = MatMul(W_in)
out_layer = MatMul(W_out)

h0 = in_layer0.forward(C0)
h1 = in_layer1.forward(C1)
h = 0.5 * (h0 + h1)
s = out_layer.forward(h)

print(h0)
print(h1)
print(h)
print("--------------------------------")
print(s)

[[-1.41285845  0.06807981 -0.29579496]]
[[-0.06705597  0.76883585 -0.03233666]]
[[-0.73995721  0.41845783 -0.16406581]]
--------------------------------
[[-1.46741015 -0.5378692  -0.65784142 -0.38909757 -0.55704964  0.98229929
  -0.59082937]]
