In [20]:
!git clone https://github.com/oreilly-japan/deep-learning-from-scratch
!cp ./deep-learning-from-scratch/ch03/sample_weight.pkl ./

fatal: destination path 'deep-learning-from-scratch' already exists and is not an empty directory.


In [21]:
import numpy as np
import sys, os
sys.path.append(
    os.path.join(os.getcwd(), 'deep-learning-from-scratch')
)
from common.functions import *
from common.gradient import numerical_gradient
from ch04.two_layer_net import TwoLayerNet

net = TwoLayerNet(
    input_size=784,
    hidden_size=5040,
    output_size=10
)
net.params['W1'].shape
net.params['b1'].shape
net.params['W2'].shape
net.params['b2'].shape

(10,)

In [22]:
x = np.random.rand(100,784)
y = net.predict(x)
#print(softmax(y))

In [23]:
#x0 = np.arange(-1000, 1000, 100)
#print(f"x0 : { x0 }")
#x1 = np.arange(-1000, 1000, 100)
#print(f"x1 : { x1 }")
x0 = np.array(
    [1,2,3,4]
)
x1 = np.array(
    [5,6,7]
)
X, Y = np.meshgrid(x0, x1)

#print(f"X : { X }")
#print(f"Y : { Y }")

# x0, x1을 1D 배열로 변환
X = X.flatten()
Y = Y.flatten()

#print(f"X : { X }")
#print(f"Y : { Y }")

print(np.array([X, Y]))
print(np.array([X, Y]).T)

[[1 2 3 4 1 2 3 4 1 2 3 4]
 [5 5 5 5 6 6 6 6 7 7 7 7]]
[[1 5]
 [2 5]
 [3 5]
 [4 5]
 [1 6]
 [2 6]
 [3 6]
 [4 6]
 [1 7]
 [2 7]
 [3 7]
 [4 7]]


In [24]:
x = np.random.rand(50,784)
t = np.random.rand(50,10)

# 가중치 업데이트
grads = net.numerical_gradient(x,t)

grads['W1'].shape
grads['b1'].shape
grads['W2'].shape
grads['b2'].shape

KeyboardInterrupt: 

In [ ]:
import numpy as np
from dataset.mnist import load_mnist
from ch04.two_layer_net import TwoLayerNet

(x_train, t_train), (x_test, t_test) = load_mnist(
    normalize=True,
    one_hot_label=True
)

network = TwoLayerNet(
    input_size=784,
    hidden_size=50,
    output_size=10
)

iters_num = 10000
train_size = x_train.shape[0]
batch_size = 100
learning_rate = 0.1

train_loss_list =  []
train_acc_list = []
test_acc_list = []

iter_per_epoch = max( train_size / batch_size, 1 )

for i in range(iters_num):
    #train_size에서 batch_size만큼 index 선택
    batch_mask = np.random.choice(
        train_size,
        batch_size
    )
    #값 선택
    x_batch = x_train[batch_mask]
    #태그 선택
    t_batch = t_train[batch_mask]


    grad = network.numerical_gradient(
        x_batch,
        t_batch
    )

    for key in ('W1', 'b1', 'W2', 'b2'):
        network.params[key] -= learning_rate * grad[key]

    loss = network.loss(x_batch, t_batch)
    train_loss_list.append(loss)

    if i % iter_per_epoch == 0:
        train_acc = network.accuracy(x_train, t_train)
        test_acc = network.accuracy(x_test, t_test)
        train_acc_list.append(train_acc)
        test_acc_list.append(test_acc)
        print(
            "train acc, test acc | " +
            str(train_acc) + ", " + str(test_acc)
        )


Done
Done
Done
Done
Converting train-images-idx3-ubyte.gz to NumPy Array ...
Done
Converting train-labels-idx1-ubyte.gz to NumPy Array ...
Done
Converting t10k-images-idx3-ubyte.gz to NumPy Array ...
Done
Converting t10k-labels-idx1-ubyte.gz to NumPy Array ...
Done
Creating pickle file ...
Done!
train acc, test acc | 0.0993, 0.1032
